"use client";

import type { Metadata } from "next";
import { Inter, Raleway } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/auth";
import { AssessmentProvider } from "@/context/assessment";

const raleway = Raleway({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AssessmentProvider>
        <AuthProvider>
          <body className={raleway.className}>{children}</body>
        </AuthProvider>
      </AssessmentProvider>
    </html>
  );
}
